### ISSUE TITLE
Randomize and Reset defaults trigger error message

### ISSUE THREAD

**Issue by demetera** [nclavaud/mininova-web-editor#21]
Dear @nclavaud 

I found some issues. Maybe it's related to missing dependencies.

Steps to reproduce:
1) Cloned repository
2) Installed yarn packages with:
`yarn install`
3) Started development server with:
`yarn start`
4) Successfully found my Mininova, selected ports
5) I can change all parameters, such as Arp, OSC, LFOs etc.
6) When I select Randomize ot Reset defaults (only) it gives me error message for Randomize:

_emit
src/App.tsx:60_
```
  57 |     return;
  58 |   }
  59 |   debugMidiMessage(message, 'Output: ');
> 60 |   output.send(message);
     | ^  61 | };
  62 | 
  63 | const onChangeOutput = () => selectPatch(emit);
```

_randomize
src/components/Controls.js:41_
```
  38 |       continue;
  39 |     }
  40 |     const value = control.range ? randomInt(...control.range) : randomInt(0, control.enum.length);
> 41 |     emit(control.msg(value));
     | ^  42 |     dispatch(patchControlChanged(controlId, value));
  43 |   }
  44 | };
```

and this for Reset Defaults:

_resetDefaults
src/components/Controls.js:30_
```
 27 | const resetDefaults = () => {
  28 |   for (let [controlId, control] of Object.entries(controls)) {
  29 |     const value = control.init;
> 30 |     emit(control.msg(value));
     | ^  31 |     dispatch(patchControlChanged(controlId, value));
  32 |   }
  33 | };
```

In terminal I see this:

_src/App.tsx
  Line 65:42:  React Hook useCallback has a missing dependency: 'output'. Either include it or remove the dependency array  react-hooks/exhaustive-deps_

Thank you for checking this.

**Comment by nclavaud** [comment]
Hi @demetera, thanks for reporting this. Looks like the "reset defaults" behavior is broken indeed.

I merged a fix, and it now works as expected for me (both "randomize" and "reset defaults"). How does it look on your side?

**Comment by demetera** [comment]
Hi @nclavaud 

Your recent commit fixed the problem. Now it's working properly.

Meanwhile I have to connect Midi in to Midi through out in Catia,
otherwise Mininova freezes when Randomizing preset, but this is not a big deal and might be
related to my system specifics.

Thanks a lot!
